# This file is a template, and might need editing before it works on your project.
# Official docker image.
before_script:
- docker info

build:
  stage: build
  tags:
    - shell-runner
  script:
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN docker.ii.org.nz
  - docker build -t docker.ii.org.nz/ii/owncloud:owncloud-apache owncloud/9.1/apache
  - docker push docker.ii.org.nz/ii/owncloud:owncloud-apache